
services:
  wordpress:
    image: wordpress:latest
    container_name: wp_site
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password #tom testat logga in med detta för att se om jag får admin behörihet.. uteslutningsmetoden liksom
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./:/var/www/html

  db:
    image: mysql:5.7
    container_name: wp_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword #kan inte logga in med detta löseord. får error
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password #ändrade till secret1 pga felstavat men de funkade inte. så får köra på detta..
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wp_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword

volumes:
  db_data:
